import { promises as fs } from "fs";
import path from "path";

import { GenerationPlan } from "../lib/models";
import { GenerationService } from "../lib/services";

async function main(): Promise<void> {

    const outputPath = path.join(
        process.cwd(),
        "sandbox-output",
        "generated-project"
    );

    // The sandbox test starts with a clean destination so that
    // repeated test runs produce the same result.
    await fs.rm(outputPath, {
        recursive: true,
        force: true
    });

    const plan: GenerationPlan = {
        outputPath,

        folders: [
            {
                path: path.join(outputPath, "docs"),
                relativePath: "docs"
            },
            {
                path: path.join(outputPath, "src"),
                relativePath: "src"
            }
        ],

        files: [
            {
                sourcePath: "manual-test/README.md",
                destinationPath: path.join(
                    outputPath,
                    "README.md"
                ),
                relativePath: "README.md",
                contents: [
                    "# Generated Project",
                    "",
                    "This project was generated by Project Genesis."
                ].join("\n")
            },
            {
                sourcePath: "manual-test/ARCHITECTURE.md",
                destinationPath: path.join(
                    outputPath,
                    "docs",
                    "ARCHITECTURE.md"
                ),
                relativePath: "docs/ARCHITECTURE.md",
                contents: [
                    "# Architecture",
                    "",
                    "This file was created by the Generation Engine."
                ].join("\n")
            },
            {
                sourcePath: "manual-test/index.ts",
                destinationPath: path.join(
                    outputPath,
                    "src",
                    "index.ts"
                ),
                relativePath: "src/index.ts",
                contents: [
                    'console.log("Generated by Project Genesis.");',
                    ""
                ].join("\n")
            }
        ],

        createdAt: new Date()
    };

    const generationService =
        new GenerationService();

    await generationService.generate(plan);

    console.log("Generation completed successfully.");
    console.log(`Output: ${outputPath}`);
    console.log(`Folders created: ${plan.folders.length}`);
    console.log(`Files created: ${plan.files.length}`);

}

main().catch((error: unknown) => {

    console.error(
        "Generation test failed.",
        error
    );

    process.exitCode = 1;

});